# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# https://www.jianshu.com/p/ac18956b0bc0


# git tag -a v0.0.3 -m "release v0.0.3"
# git push origin v0.0.3
# goreleaser --rm-dist

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    hooks:
      pre: dep ensure
archives:

  - files:
      - src: LICENSE
      - src: README.md
      - src: conf/*
      - src: scripts/*
      - src: templates/*
      - src: public/*

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
