title: zzz
dev: false
frequency: 2
lang: "go"
dirfilter:
- tmp
- .git
- scripts
- vendor
- logs
ext:
- go
enablerun: true
action:
  before:
  - echo "before"
  - gofmt -w ./
  - find . -name ".DS_Store" -print -delete
  after:
  - zzz -v
  exit:
  - echo "exit zzz"
link: https://github.com/midoks/zzz
